feat: :sparkles: new yml login user

diff --git a/.github/workflows/loginUsers-ci-cd.yml b/.github/workflows/loginUsers-ci-cd.yml
--- a/.github/workflows/loginUsers-ci-cd.yml
+++ b/.github/workflows/loginUsers-ci-cd.yml
@@ -1,14 +1,13 @@
-name: Docker Image CI/CD for Login User Microservice
+name: Docker Image CI/CD for Product Service - Create
 
 on:
   push:
     paths:
       - 'Backend_tshirtop1/Authentication_and_Authorization/login_user/**'
-    branches:
-      - 'test'
+    branches: ["test"]
   pull_request:
     paths:
-      - 'Backend_tshirtop1/Authentication_and_Authorization/register_user/**'
+      - Backend_tshirtop1/Authentication_and_Authorization/login_user/**'
     branches: ["QA", "main"]
 
 jobs:
@@ -24,7 +23,74 @@ jobs:
     - name: Log in to Docker Hub
       uses: docker/login-action@v2
       with:
-        #username: ${{ secrets.DOCKER_USERNAME }}
-        #password: ${{ secrets.DOCKER_PASSWORD }}
+        username: ${{ secrets.DOCKER_USERNAME }}
+        password: ${{ secrets.DOCKER_PASSWORD }}
 
-    
+    # Paso 3: Construir la imagen Docker usando los secrets
+    - name: Build Docker image
+      run: |
+         docker build Backend_tshirtop1/Authentication_and_Authorization/login_user/**/. --file Backend_tshirtop1/Authentication_and_Authorization/login_user/Dockerfile \
+          --build-arg DB_NAME=${{ secrets.REGISTER_USER_BD }} \
+          --build-arg DB_USER=${{ secrets.REGISTER_USER_U }} \
+          --build-arg DB_PASSWORD=${{ secrets.REGISTER_USER_PASS }} \
+          --build-arg DB_HOST=${{ secrets.REGISTER_USER_HOST }} \
+          --build-arg DB_DIALECT=${{ secrets.REGISTER_USER_DIALECT }} \
+          -t ${{ secrets.DOCKER_USERNAME }}/register-user-service:latest
+
+    # Paso 4: Subir la imagen a Docker Hub
+    - name: Push Docker image to Docker Hub
+      run: |
+        docker push ${{ secrets.DOCKER_USERNAME }}/login-user-service:latest
+
+  deploy:
+    needs: build
+    runs-on: ubuntu-latest
+
+    steps:
+    # Paso 1: Conectar al servidor EC2 usando SSH
+    - name: Deploy to EC2
+      uses: appleboy/ssh-action@v0.1.8
+      with:
+        host: ${{ secrets.EC2_HOST_LOGIN_USER }}
+        username: ${{ secrets.EC2_USER }}
+        key: ${{ secrets.EC2_SSH_KEY }}
+        port: 22
+        script: |
+          # Verificar si Docker está instalado
+          if ! command -v docker &> /dev/null; then
+            echo "==> Installing Docker"
+            sudo yum update -y
+            sudo yum install -y docker
+            sudo service docker start
+            sudo usermod -a -G docker ec2-user
+          fi
+
+          # Detener y eliminar el contenedor previo si existe
+          echo "Deteniendo y eliminando contenedor previo..."
+          sudo docker stop create-product-service || true
+          sudo docker rm create-product-service || true
+          
+          # Descargar la última imagen desde Docker Hub
+          echo "Actualizando imagen desde Docker Hub..."
+          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/login-user-service:latest
+          
+          # Ejecutar el nuevo contenedor en el puerto 3306
+          echo "Ejecutando nuevo contenedor en el puerto ${{
+            secrets.SERVER_PORT_CREATE_PRODUCT }}..."
+          sudo docker run -d \
+            --name register-user-service \
+            -p 3306:${{ secrets.SERVER_PORT_LOGIN_USER }} \
+            -e DB_NAME=${{ secrets.REGISTER_USER_BD }} \
+            -e DB_USER=${{ secrets.REGISTER_USER_U }} \
+            -e DB_PASSWORD=${{ secrets.REGISTER_USER_PASS }} \
+            -e DB_HOST=${{ secrets.REGISTER_USER_HOST }} \
+            -e DB_DIALECT=${{ secrets.REGISTER_USER_DIALECT }} \
+            ${{ secrets.DOCKER_USERNAME }}/register-user-service:latest
+
+          # Verificar que el contenedor esté corriendo
+          if sudo docker ps -f name=create-product-service | grep create-product-service; then
+            echo "Contenedor corriendo correctamente."
+          else
+            echo "Error al iniciar el contenedor. Revisa los logs."
+            exit 1
+          fi
