Update product-create-ci-cd.yml

diff --git a/.github/workflows/product-create-ci-cd.yml b/.github/workflows/product-create-ci-cd.yml
--- a/.github/workflows/product-create-ci-cd.yml
+++ b/.github/workflows/product-create-ci-cd.yml
@@ -48,48 +48,45 @@ jobs:
     steps:
     # Paso 1: Conectar al servidor EC2 usando SSH
     - name: Deploy to EC2
-      uses: appleboy/ssh-action@v0.1.8
-      with:
-        host: ${{ secrets.EC2_HOST_CREATE_PRODUCT }}
-        username: ${{ secrets.EC2_USER }}
-        key: ${{ secrets.EC2_SSH_KEY }}
-        port: 22
-        script: |
-          # Verificar si Docker está instalado
-          if ! command -v docker &> /dev/null; then
-            echo "==> Installing Docker"
-            sudo yum update -y
-            sudo yum install -y docker
-            sudo service docker start
-            sudo usermod -a -G docker ec2-user
-          fi
+  uses: appleboy/ssh-action@v0.1.8
+  with:
+    host: ${{ secrets.EC2_HOST_CREATE_PRODUCT }}
+    username: ${{ secrets.EC2_USER }}
+    key: ${{ secrets.EC2_SSH_KEY }}
+    port: 22
+    script: |
+      # Verificar si Docker está instalado
+      if ! command -v docker &> /dev/null; then
+        echo "==> Installing Docker"
+        sudo yum update -y
+        sudo yum install -y docker
+        sudo service docker start
+        sudo usermod -a -G docker ec2-user
+      fi
+      # Detener y eliminar el contenedor previo si existe
+      echo "Deteniendo y eliminando contenedor previo..."
+      sudo docker stop create-product-service || true
+      sudo docker rm create-product-service || true
+      # Descargar la última imagen desde Docker Hub
+      echo "Actualizando imagen desde Docker Hub..."
+      sudo docker pull ${{ secrets.DOCKER_USERNAME }}/create-product-service:latest
+      # Ejecutar el nuevo contenedor
+      echo "Ejecutando nuevo contenedor en el puerto..."
+      sudo docker run -d \
+        --name create-product-service \
+        -p 3000:3000 \
+        -e DB_NAME=${{ secrets.PRODUCTS_DB }} \
+        -e DB_USER=${{ secrets.PRODUCTS_USER_U }} \
+        -e DB_PASSWORD=${{ secrets.REGISTER_PRODUCT_PASS }} \
+        -e DB_HOST=${{ secrets.EC2_HOST_REGISTER_PRODUCT }} \
+        -e DB_PORT=${{ secrets.SERVER_PORT_REGISTER_PRODUCT }} \
+        ${{ secrets.DOCKER_USERNAME }}/create-product-service:latest
+      # Verificar que el contenedor esté corriendo
+      if sudo docker ps -f name=create-product-service | grep create-product-service; then
+        echo "Contenedor corriendo correctamente."
+      else
+        echo "Error al iniciar el contenedor. Revisa los logs."
+        exit 1
+      fi
+    debug: true
 
-          # Detener y eliminar el contenedor previo si existe
-          echo "Deteniendo y eliminando contenedor previo..."
-          sudo docker stop create-product-service || true
-          sudo docker rm create-product-service || true
-
-          # Descargar la última imagen desde Docker Hub
-          echo "Actualizando imagen desde Docker Hub..."
-          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/create-product-service:latest
-
-          # Ejecutar el nuevo contenedor en el puerto 3000
-          echo "Ejecutando nuevo contenedor en el puerto ${{
-            secrets.PRODUCTS_DB_PORT }}..."
-          sudo docker run -d \
-            --name create-product-service \
-            -p 3000:${{ secrets.SERVER_PORT_REGISTER_PRODUCT }} \
-            -e DB_NAME=${{ secrets.PRODUCTS_DB }} \
-            -e DB_USER=${{ secrets.PRODUCTS_USER_U }} \
-            -e DB_PASSWORD=${{ secrets.REGISTER_PRODUCT_PASS }} \
-            -e DB_HOST=${{ secrets.HOST_PRODUCT_DB }} \
-            -e DB_PORT=${{ secrets.SERVER_PORT_PRODUCTS }} \
-            ${{ secrets.DOCKER_USERNAME }}/create-product-service:latest
-
-          # Verificar que el contenedor esté corriendo
-          if sudo docker ps -f name=create-product-service | grep create-product-service; then
-            echo "Contenedor corriendo correctamente."
-          else
-            echo "Error al iniciar el contenedor. Revisa los logs."
-            exit 1
-          fi
